package ru.axmor.trial.tracker.repository;

import ru.axmor.trial.tracker.model.Issue;

import java.util.List;

/**
 * Interface that operates with issues in database.
 */
public interface IssueRepository {
    /**
     * Save issue in database.
     *
     * @param issue issue object that prepared to be saved
     * @return same issue with autogenerated id
     */
    Issue save(Issue issue);

    /**
     * Update info about issue.
     *
     * @param issue issue that contains all updated info
     * @return same issue object
     */
    Issue update(Issue issue);

    /**
     * Find issue in database with received id.
     *
     * @param id issue ID
     * @return found issue
     */
    Issue getById(long id);

    /**
     * Get all issues form database.
     *
     * @return issues list
     */
    List<Issue> getAll();
}
